### PR TITLE
Update the repository for the new RoboCup set up

### PR DESCRIPTION
**Pull request by ysims**
The new RoboCup set up uses
- Webots R2022b (release is on GitHub)
- hlvs_webots repository from the TC, containing the robocup environment files

This PR
- Removes the webots subtree (get the R2022b release rather than building from source)
- Converts the NUgus proto files to R2022b version
- Updates the robocup field proto based on the hlvs_webots repository, keeping in (and updating) our changes for vision data collection. Note: proto scriping now uses JavaScript rather than Lua.
- Updates the kid world with new protos and the externproto declarations

There are many files changed because the subtree has been removed. You can view the individual commits to see what else has changed.

Documentation update at NUbots/NUbook#273

### CODE REVIEW

**Review by LachlanCourt — DISMISSED** [review]
LGTM

**Comment by ysims** [comment]
@Tom0Brien I have got it moving through the states past SET now. I sync'd the NUbots fork of `hlvs_webots` with the original and also pulled GameController and ran `ant` again, then it seemed to work.

**Review by Tom0Brien — DISMISSED** [review]
I am still having issues on my end with sim freezing. Could be an issue on my end though.

LGTM

**Comment by ysims** [comment]
Can I get another review/approval? Had to fix up merge conflicts with the vision PR going in.

**Review by Tom0Brien — APPROVED** [review]

**Pull request merged**
