### PR TITLE
Add touch sensor code blocks to NUgus.proto

### PR DESCRIPTION
**Pull request by CampbellRoss**

### CODE REVIEW

**Comment by ysims** [comment]
https://github.blog/2018-01-29-commit-together-with-co-authors/ make sure @NDxiura is given github credit for this as well when this is merged, since making a new branch will probably not show that he did this

**Comment by CampbellRoss** [comment]
> https://github.blog/2018-01-29-commit-together-with-co-authors/ make sure @NDxiura is given github credit for this as well when this is merged, since making a new branch will probably not show that he did this

Okay, will do. Thanks!

**Comment by ysims** [comment]
Someone should test this and make sure it runs fine, and also address @moosahassanx 's [review on the other PR ](https://github.com/NUbots/NUWebots/pull/30#issuecomment-832379111) (add comments)

**Comment by SamMcFarlane** [comment]
Tested it and it works well.

**Comment by xXBenjaminYoungXx** [comment]
Has @NDxiura been credited?

**Review by ysims — COMMENTED** [review]
There are extra jpg files in this PR that need to be removed.

**Review by ysims — APPROVED** [review]
This is probably ok now.

**Pull request merged**
